import { AudioAssetDefinition } from "@/services/audio/types";

/**
 * English Side Quest Audio Manifest.
 *
 * Spoken vocabulary and instructions for English learning paths.
 */
export const ENGLISH_MANIFEST: Record<string, AudioAssetDefinition> = {
  // Vocabulary / Greetings
  english_word_hello: {
    key: "english_word_hello",
    locale: "en",
    voice: "narrator_en",
    category: "word",
    file: require("../files/en_word_hello_v1.m4a"),
    transcript: "Hello",
    reviewStatus: "approved",
    durationMs: 700,
    version: 1,
  },
  english_word_goodbye: {
    key: "english_word_goodbye",
    locale: "en",
    voice: "narrator_en",
    category: "word",
    file: require("../files/en_word_goodbye_v1.m4a"),
    transcript: "Goodbye",
    reviewStatus: "approved",
    durationMs: 750,
    version: 1,
  },
  english_word_apple: {
    key: "english_word_apple",
    locale: "en",
    voice: "narrator_en",
    category: "word",
    file: require("../files/en_word_apple_v1.m4a"),
    transcript: "Apple",
    reviewStatus: "approved",
    durationMs: 650,
    version: 1,
  },
  english_word_cat: {
    key: "english_word_cat",
    locale: "en",
    voice: "narrator_en",
    category: "word",
    file: require("../files/en_word_cat_v1.m4a"),
    transcript: "Cat",
    reviewStatus: "approved",
    durationMs: 600,
    version: 1,
  },
  english_word_dog: {
    key: "english_word_dog",
    locale: "en",
    voice: "narrator_en",
    category: "word",
    file: require("../files/en_word_dog_v1.m4a"),
    transcript: "Dog",
    reviewStatus: "approved",
    durationMs: 600,
    version: 1,
  },
  english_word_red: {
    key: "english_word_red",
    locale: "en",
    voice: "narrator_en",
    category: "word",
    file: require("../files/en_word_red_v1.m4a"),
    transcript: "Red",
    reviewStatus: "approved",
    durationMs: 600,
    version: 1,
  },
  english_word_blue: {
    key: "english_word_blue",
    locale: "en",
    voice: "narrator_en",
    category: "word",
    file: require("../files/en_word_blue_v1.m4a"),
    transcript: "Blue",
    reviewStatus: "approved",
    durationMs: 600,
    version: 1,
  },
  english_num_1: {
    key: "english_num_1",
    locale: "en",
    voice: "narrator_en",
    category: "number",
    file: require("../files/en_num_1_v1.m4a"),
    transcript: "One",
    reviewStatus: "approved",
    durationMs: 550,
    version: 1,
  },
  english_num_2: {
    key: "english_num_2",
    locale: "en",
    voice: "narrator_en",
    category: "number",
    file: require("../files/en_num_2_v1.m4a"),
    transcript: "Two",
    reviewStatus: "approved",
    durationMs: 550,
    version: 1,
  },
  english_num_3: {
    key: "english_num_3",
    locale: "en",
    voice: "narrator_en",
    category: "number",
    file: require("../files/en_num_3_v1.m4a"),
    transcript: "Three",
    reviewStatus: "approved",
    durationMs: 550,
    version: 1,
  },

  // Spoken Instructions
  en_inst_listen_hello: {
    key: "en_inst_listen_hello",
    locale: "en",
    voice: "narrator_en",
    category: "instruction",
    file: require("../files/en_inst_listen_hello_v1.m4a"),
    transcript: 'Listen and tap "Hello"',
    reviewStatus: "approved",
    durationMs: 1400,
    version: 1,
  },
  en_inst_listen_goodbye: {
    key: "en_inst_listen_goodbye",
    locale: "en",
    voice: "narrator_en",
    category: "instruction",
    file: require("../files/en_inst_listen_goodbye_v1.m4a"),
    transcript: 'Listen and tap "Goodbye"',
    reviewStatus: "approved",
    durationMs: 1400,
    version: 1,
  },
};
