import { AudioAssetDefinition } from "@/services/audio/types";

/**
 * Khmer Educational Audio Manifest.
 *
 * CRITICAL SAFETY RULE:
 * Khmer pronunciation quality is essential for child education.
 * All AI-generated Khmer educational assets default to `reviewStatus: "needs_review"`
 * until explicitly vetted and approved by a native speaker.
 */
export const KHMER_MANIFEST: Record<string, AudioAssetDefinition> = {
  // --- Khmer Consonants (Letter Pronunciation) ---
  khmer_letter_ka: {
    key: "khmer_letter_ka",
    locale: "km",
    voice: "narrator_km",
    category: "letter",
    file: require("../files/km_letter_ka_v1.m4a"),
    transcript: "ក",
    reviewStatus: "needs_review", // Must be verified by native speaker
    durationMs: 650,
    version: 1,
  },
  khmer_letter_kha: {
    key: "khmer_letter_kha",
    locale: "km",
    voice: "narrator_km",
    category: "letter",
    file: require("../files/km_letter_kha_v1.m4a"),
    transcript: "ខ",
    reviewStatus: "needs_review",
    durationMs: 650,
    version: 1,
  },
  khmer_letter_ko: {
    key: "khmer_letter_ko",
    locale: "km",
    voice: "narrator_km",
    category: "letter",
    file: require("../files/km_letter_ko_v1.m4a"),
    transcript: "គ",
    reviewStatus: "needs_review",
    durationMs: 650,
    version: 1,
  },

  // --- Khmer Numbers ---
  khmer_num_1: {
    key: "khmer_num_1",
    locale: "km",
    voice: "narrator_km",
    category: "number",
    file: require("../files/km_num_1_v1.m4a"),
    transcript: "១ (មួយ)",
    reviewStatus: "needs_review",
    durationMs: 600,
    version: 1,
  },
  khmer_num_2: {
    key: "khmer_num_2",
    locale: "km",
    voice: "narrator_km",
    category: "number",
    file: require("../files/km_num_2_v1.m4a"),
    transcript: "២ (ពីរ)",
    reviewStatus: "needs_review",
    durationMs: 600,
    version: 1,
  },
  khmer_num_3: {
    key: "khmer_num_3",
    locale: "km",
    voice: "narrator_km",
    category: "number",
    file: require("../files/km_num_3_v1.m4a"),
    transcript: "៣ (បី)",
    reviewStatus: "needs_review",
    durationMs: 600,
    version: 1,
  },
  khmer_num_4: {
    key: "khmer_num_4",
    locale: "km",
    voice: "narrator_km",
    category: "number",
    file: require("../files/km_num_4_v1.m4a"),
    transcript: "៤ (បួន)",
    reviewStatus: "needs_review",
    durationMs: 600,
    version: 1,
  },
  khmer_num_5: {
    key: "khmer_num_5",
    locale: "km",
    voice: "narrator_km",
    category: "number",
    file: require("../files/km_num_5_v1.m4a"),
    transcript: "៥ (ប្រាំ)",
    reviewStatus: "needs_review",
    durationMs: 600,
    version: 1,
  },

  // --- Khmer Colors ---
  khmer_color_red: {
    key: "khmer_color_red",
    locale: "km",
    voice: "narrator_km",
    category: "word",
    file: require("../files/km_color_red_v1.m4a"),
    transcript: "ក្រហម",
    reviewStatus: "needs_review",
    durationMs: 650,
    version: 1,
  },
  khmer_color_blue: {
    key: "khmer_color_blue",
    locale: "km",
    voice: "narrator_km",
    category: "word",
    file: require("../files/km_color_blue_v1.m4a"),
    transcript: "ខៀវ",
    reviewStatus: "needs_review",
    durationMs: 600,
    version: 1,
  },
  khmer_color_green: {
    key: "khmer_color_green",
    locale: "km",
    voice: "narrator_km",
    category: "word",
    file: require("../files/km_color_green_v1.m4a"),
    transcript: "បៃតង",
    reviewStatus: "needs_review",
    durationMs: 650,
    version: 1,
  },
  khmer_color_yellow: {
    key: "khmer_color_yellow",
    locale: "km",
    voice: "narrator_km",
    category: "word",
    file: require("../files/km_color_yellow_v1.m4a"),
    transcript: "លឿង",
    reviewStatus: "needs_review",
    durationMs: 600,
    version: 1,
  },

  // --- Khmer Animals / Vocabulary ---
  khmer_word_elephant: {
    key: "khmer_word_elephant",
    locale: "km",
    voice: "narrator_km",
    category: "word",
    file: require("../files/km_word_elephant_v1.m4a"),
    transcript: "ដំរី",
    reviewStatus: "needs_review",
    durationMs: 650,
    version: 1,
  },
  khmer_word_dog: {
    key: "khmer_word_dog",
    locale: "km",
    voice: "narrator_km",
    category: "word",
    file: require("../files/km_word_dog_v1.m4a"),
    transcript: "ឆ្កែ",
    reviewStatus: "needs_review",
    durationMs: 600,
    version: 1,
  },
  khmer_word_fish: {
    key: "khmer_word_fish",
    locale: "km",
    voice: "narrator_km",
    category: "word",
    file: require("../files/km_word_fish_v1.m4a"),
    transcript: "ត្រី",
    reviewStatus: "needs_review",
    durationMs: 600,
    version: 1,
  },
  khmer_word_monkey: {
    key: "khmer_word_monkey",
    locale: "km",
    voice: "narrator_km",
    category: "word",
    file: require("../files/km_word_monkey_v1.m4a"),
    transcript: "ស្វា",
    reviewStatus: "needs_review",
    durationMs: 600,
    version: 1,
  },

  // --- Spoken Lesson Instructions ---
  km_inst_tap_letter_ka: {
    key: "km_inst_tap_letter_ka",
    locale: "km",
    voice: "narrator_km",
    category: "instruction",
    file: require("../files/km_inst_tap_letter_ka_v1.m4a"),
    transcript: "ចុចលើតួអក្សរ ក",
    reviewStatus: "needs_review",
    durationMs: 1500,
    version: 1,
  },
  km_inst_tap_red: {
    key: "km_inst_tap_red",
    locale: "km",
    voice: "narrator_km",
    category: "instruction",
    file: require("../files/km_inst_tap_red_v1.m4a"),
    transcript: "ចុចលើពណ៌ក្រហម",
    reviewStatus: "needs_review",
    durationMs: 1400,
    version: 1,
  },
  km_inst_which_num_3: {
    key: "km_inst_which_num_3",
    locale: "km",
    voice: "narrator_km",
    category: "instruction",
    file: require("../files/km_inst_which_num_3_v1.m4a"),
    transcript: "តើមួយណាជាលេខ ៣?",
    reviewStatus: "needs_review",
    durationMs: 1500,
    version: 1,
  },
  km_inst_match_animals: {
    key: "km_inst_match_animals",
    locale: "km",
    voice: "narrator_km",
    category: "instruction",
    file: require("../files/km_inst_match_animals_v1.m4a"),
    transcript: "ភ្ជាប់រូបសត្វ និងឈ្មោះដែលត្រូវគ្នា",
    reviewStatus: "needs_review",
    durationMs: 1800,
    version: 1,
  },
};
